/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Button, TextField } from '@mui/material';
import Screenshot20230329AtImage from 'src/assets/images/Welcome_Screenshot_2023_03_29_at_8_43_1.png';
import { styled } from '@mui/material/styles';

const Property1Default = styled('div')({
  backgroundColor: `rgba(220, 220, 220, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `900px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 25px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Frame1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Headers = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `383.43px`,
  margin: `0px`,
});

const Screenshot20230329At = styled('img')({
  height: `152px`,
  width: `331.75px`,
  margin: `0px`,
});

const Headers1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `383.43px`,
  margin: `30px 0px 0px 0px`,
});

const HowMuchCarCanYouAffo = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(35, 119, 6, 1)`,
  fontStyle: `normal`,
  fontFamily: `Plus Jakarta Sans`,
  fontWeight: `800`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `40px`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Form = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `440.47px`,
  width: `414.5px`,
  margin: `30px 0px 0px 0px`,
});

const CharName = styled(TextField)({
  width: `412px`,
  height: `38px`,
  position: `absolute`,
  left: `1px`,
  top: `0px`,
});

const Group6 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `414.5px`,
  height: `37.62px`,
  left: `0px`,
  top: `68px`,
});

const Age = styled(TextField)({
  width: `197.72px`,
  height: `37.62px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Gender = styled(TextField)({
  width: `197.72px`,
  height: `37.62px`,
  position: `absolute`,
  left: `217px`,
  top: `0px`,
});

const Group9 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `414.5px`,
  height: `37.62px`,
  left: `0px`,
  top: `136px`,
});

const Age1 = styled(TextField)({
  width: `197.72px`,
  height: `37.62px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Gender1 = styled(TextField)({
  width: `197.72px`,
  height: `37.62px`,
  position: `absolute`,
  left: `217px`,
  top: `0px`,
});

const Group10 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `414.5px`,
  height: `37.62px`,
  left: `0px`,
  top: `203px`,
});

const Age2 = styled(TextField)({
  width: `197.72px`,
  height: `37.62px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Gender2 = styled(TextField)({
  width: `197.72px`,
  height: `37.62px`,
  position: `absolute`,
  left: `217px`,
  top: `0px`,
});

const Group11 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `414.5px`,
  height: `37.62px`,
  left: `0px`,
  top: `271px`,
});

const Age3 = styled(TextField)({
  width: `197.72px`,
  height: `37.62px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Gender3 = styled(TextField)({
  width: `197.72px`,
  height: `37.62px`,
  position: `absolute`,
  left: `217px`,
  top: `0px`,
});

const Frame27 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `30px 5px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `414.5px`,
  left: `0px`,
  top: `338px`,
});

const ButtonContained = styled(Button)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
  color: theme.palette['Success']['Contrast'],
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `15px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
}));

function Welcome(props) {
  return (
    <Property1Default className={props.className}>
      <Frame1>
        <Headers>
          <Screenshot20230329At
            src={Screenshot20230329AtImage}
            loading="lazy"
            alt={'Screenshot 2023-03-29 at 8.43 1'}
          />
        </Headers>
        <Headers1>
          <HowMuchCarCanYouAffo>
            {`How much Car can you Afford?`}
          </HowMuchCarCanYouAffo>
        </Headers1>
        <Form>
          <CharName variant="outlined" size="medium" label={`Annual Income`} />
          <Group6>
            <Age variant="outlined" size="medium" label={`Credit Score`} />
            <Gender
              variant="outlined"
              size="medium"
              label={`Monthly Rent/Mortgage`}
            />
          </Group6>
          <Group9>
            <Age1
              variant="outlined"
              size="medium"
              label={`Monthly Min. Credit Card`}
            />
            <Gender1
              variant="outlined"
              size="medium"
              label={`Monthly Loan Payments`}
            />
          </Group9>
          <Group10>
            <Age2
              variant="outlined"
              size="medium"
              label={`Expected Miles per Year`}
            />
            <Gender2
              variant="outlined"
              size="medium"
              label={`Expected Down Payment`}
            />
          </Group10>
          <Group11>
            <Age3
              variant="outlined"
              size="medium"
              label={`Current Vehicle Trade-In Value`}
            />
            <Gender3
              variant="outlined"
              size="medium"
              label={`Current Vehicle Debt`}
            />
          </Group11>
          <Frame27>
            <ButtonContained
              variant="contained"
              disabled={false}
              size={'large'}
              color={'success'}
            >
              {'Calculate my Price Range'}
            </ButtonContained>
          </Frame27>
        </Form>
      </Frame1>
    </Property1Default>
  );
}

export default Welcome;
